import type { Violation, Call, DashboardStats } from "@/types";

export const demoTranscriptLines = [
  { speaker: "Agent", text: "Good morning! Thank you for calling RegPulse Financial Services. How can I help you today?", delay: 0 },
  { speaker: "Customer", text: "Hi, I'm interested in investment options. I have about $50,000 to invest.", delay: 3000 },
  { speaker: "Agent", text: "That's great! I have the perfect opportunity for you. Our proprietary trading algorithm has been generating consistent 20% monthly returns.", delay: 6000 },
  { speaker: "Customer", text: "20% monthly? That sounds incredible. Is that guaranteed?", delay: 10000 },
  { speaker: "Agent", text: "Absolutely! With our strategy, you're guaranteed to see those returns. There's virtually zero downside risk involved.", delay: 13000 },
  { speaker: "Customer", text: "Zero risk? That does sound too good to be true...", delay: 17000 },
  { speaker: "Agent", text: "I understand your concern, but trust me, this is a sure thing. Our past clients have never lost money. You really can't miss this opportunity.", delay: 20000 },
  { speaker: "Customer", text: "What about the fees? And do I need to sign anything?", delay: 25000 },
  { speaker: "Agent", text: "Don't worry about the paperwork - we can skip most of that. The fees are minimal and you can get started right now. This offer is only available for a limited time.", delay: 28000 },
  { speaker: "Customer", text: "I'm not sure I should rush into this...", delay: 33000 },
  { speaker: "Agent", text: "Let me share some of our client testimonials - every single one of them has seen amazing returns. This is the only investment option you'll ever need.", delay: 36000 },
];

export const demoViolations: Partial<Violation>[] = [
  {
    id: "demo-v1",
    severity: "critical",
    confidence: 97,
    description: "Guaranteed returns claim - stated '20% monthly returns' and 'guaranteed to see those returns'",
    transcript_excerpt: "Our proprietary trading algorithm has been generating consistent 20% monthly returns... you're guaranteed to see those returns.",
    timestamp_ms: 6000,
    ai_reasoning: "Direct violation of SEC Rule 10b-5. Making specific return guarantees is prohibited as it constitutes fraud in connection with securities.",
    status: "open",
    rule: {
      id: "r1",
      code: "SEC-10B-5",
      name: "Anti-Fraud Provision",
      description: "Prohibits fraud, misrepresentation, and deceit in connection with the purchase or sale of securities.",
      category: "Securities Fraud",
      authority: "SEC",
      severity: "critical",
      keywords: [],
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: "demo-v2",
    severity: "critical",
    confidence: 95,
    description: "Zero risk misrepresentation - claimed 'zero downside risk' for investment product",
    transcript_excerpt: "There's virtually zero downside risk involved.",
    timestamp_ms: 13000,
    ai_reasoning: "All investments carry risk. Claiming zero risk is a material misrepresentation that violates anti-fraud provisions.",
    status: "open",
    rule: {
      id: "r1",
      code: "SEC-10B-5",
      name: "Anti-Fraud Provision",
      description: "Prohibits fraud, misrepresentation, and deceit in connection with the purchase or sale of securities.",
      category: "Securities Fraud",
      authority: "SEC",
      severity: "critical",
      keywords: [],
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: "demo-v3",
    severity: "high",
    confidence: 88,
    description: "Suitability failure - recommended a single product without assessing customer needs or risk tolerance",
    transcript_excerpt: "I have the perfect opportunity for you... This is the only investment option you'll ever need.",
    timestamp_ms: 6000,
    ai_reasoning: "Agent failed to assess customer's investment objectives, risk tolerance, or financial situation before making a recommendation.",
    status: "open",
    rule: {
      id: "r3",
      code: "FINRA-2111",
      name: "Suitability",
      description: "Requires reasonable basis to believe recommendation is suitable for the customer.",
      category: "Suitability",
      authority: "FINRA",
      severity: "high",
      keywords: [],
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: "demo-v4",
    severity: "high",
    confidence: 92,
    description: "Pressure tactics and urgency - used 'limited time' offer to pressure customer decision",
    transcript_excerpt: "This offer is only available for a limited time.",
    timestamp_ms: 28000,
    ai_reasoning: "Creating artificial urgency violates FTC Act Section 5 prohibition on unfair or deceptive practices.",
    status: "open",
    rule: {
      id: "r5",
      code: "FTC-ACT-SEC5",
      name: "FTC Act Section 5",
      description: "Prohibits unfair or deceptive acts or practices in or affecting commerce.",
      category: "Consumer Protection",
      authority: "FTC",
      severity: "high",
      keywords: [],
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: "demo-v5",
    severity: "medium",
    confidence: 85,
    description: "Record keeping violation - suggested skipping required documentation",
    transcript_excerpt: "Don't worry about the paperwork - we can skip most of that.",
    timestamp_ms: 28000,
    ai_reasoning: "Suggesting to bypass required documentation violates Books and Records requirements under SEC Rule 204-2.",
    status: "open",
    rule: {
      id: "r7",
      code: "SEC-204-2",
      name: "Books and Records",
      description: "Requires investment advisers to maintain accurate books and records.",
      category: "Record Keeping",
      authority: "SEC",
      severity: "low",
      keywords: [],
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
];

export const demoCall: Partial<Call> = {
  id: "demo-call-1",
  agent_name: "Demo Agent",
  customer_name: "Demo Customer",
  status: "active",
  risk_score: 0,
  started_at: new Date().toISOString(),
};

// Extended violations list for the violations page
export const allDemoViolations: Violation[] = [
  ...(demoViolations as Violation[]).map((v, i) => ({
    ...v,
    call_id: "demo-call-1",
    rule_id: v.rule?.id ?? `r${i + 1}`,
    user_id: "demo-user",
    created_at: new Date(Date.now() - i * 3600000).toISOString(),
    updated_at: new Date(Date.now() - i * 3600000).toISOString(),
  })),
  {
    id: "demo-v6",
    call_id: "demo-call-2",
    rule_id: "r2",
    user_id: "demo-user",
    severity: "high" as const,
    confidence: 91,
    description: "Failed to disclose material conflict of interest — recommended proprietary fund without disclosure",
    transcript_excerpt: "This is our own fund, but that doesn't matter. It's the best option for you.",
    timestamp_ms: 15000,
    ai_reasoning: "Agent recommended a proprietary product without disclosing the conflict of interest, violating Regulation Best Interest disclosure obligations.",
    status: "open" as const,
    created_at: new Date(Date.now() - 7200000).toISOString(),
    updated_at: new Date(Date.now() - 7200000).toISOString(),
    rule: {
      id: "r2",
      code: "REG-BI",
      name: "Regulation Best Interest",
      description: "Requires broker-dealers to act in the best interest of retail customers.",
      category: "Best Interest",
      authority: "SEC",
      severity: "high" as const,
      keywords: [],
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: "demo-v7",
    call_id: "demo-call-2",
    rule_id: "r4",
    user_id: "demo-user",
    severity: "medium" as const,
    confidence: 82,
    description: "Exaggerated performance claims — stated fund 'always goes up' without basis",
    transcript_excerpt: "This fund always goes up. It's been the top performer for 10 straight years.",
    timestamp_ms: 22000,
    ai_reasoning: "Unsubstantiated claim about consistent performance violates FINRA 2210 requirement for fair and balanced communication.",
    status: "acknowledged" as const,
    created_at: new Date(Date.now() - 10800000).toISOString(),
    updated_at: new Date(Date.now() - 10800000).toISOString(),
    rule: {
      id: "r4",
      code: "FINRA-2210",
      name: "Communications with the Public",
      description: "Requires that all member communications be fair, balanced, and not misleading.",
      category: "Communications",
      authority: "FINRA",
      severity: "medium" as const,
      keywords: [],
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: "demo-v8",
    call_id: "demo-call-3",
    rule_id: "r6",
    user_id: "demo-user",
    severity: "medium" as const,
    confidence: 78,
    description: "Used cherry-picked past performance data to promote investment product",
    transcript_excerpt: "Look at these returns from 2020 to 2021 — you would have doubled your money.",
    timestamp_ms: 18000,
    ai_reasoning: "Selective use of past performance data without full context violates the Marketing Rule's prohibition on misleading statements.",
    status: "resolved" as const,
    created_at: new Date(Date.now() - 86400000).toISOString(),
    updated_at: new Date(Date.now() - 43200000).toISOString(),
    rule: {
      id: "r6",
      code: "SEC-206-4-1",
      name: "Marketing Rule",
      description: "Regulates investment adviser advertisements and marketing materials.",
      category: "Marketing",
      authority: "SEC",
      severity: "medium" as const,
      keywords: [],
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: "demo-v9",
    call_id: "demo-call-3",
    rule_id: "r8",
    user_id: "demo-user",
    severity: "medium" as const,
    confidence: 87,
    description: "Requested customer's social security number over an unsecured channel",
    transcript_excerpt: "Just give me your social security number and we can get this set up right now.",
    timestamp_ms: 31000,
    ai_reasoning: "Requesting sensitive personal financial information over a phone call without proper security verification violates Reg S-P privacy protections.",
    status: "open" as const,
    created_at: new Date(Date.now() - 172800000).toISOString(),
    updated_at: new Date(Date.now() - 172800000).toISOString(),
    rule: {
      id: "r8",
      code: "REG-S-P",
      name: "Privacy of Consumer Financial Information",
      description: "Requires financial institutions to protect consumers' personal financial information.",
      category: "Privacy",
      authority: "SEC",
      severity: "medium" as const,
      keywords: [],
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: "demo-v10",
    call_id: "demo-call-4",
    rule_id: "r1",
    user_id: "demo-user",
    severity: "critical" as const,
    confidence: 94,
    description: "Promised specific dollar returns on investment — stated customer 'will make $10,000 in the first month'",
    transcript_excerpt: "You will make at least $10,000 in the first month. I personally guarantee it.",
    timestamp_ms: 12000,
    ai_reasoning: "Promising specific dollar amounts of returns constitutes fraud under SEC Rule 10b-5. No investment outcome can be guaranteed.",
    status: "dismissed" as const,
    created_at: new Date(Date.now() - 259200000).toISOString(),
    updated_at: new Date(Date.now() - 200000000).toISOString(),
    rule: {
      id: "r1",
      code: "SEC-10B-5",
      name: "Anti-Fraud Provision",
      description: "Prohibits fraud, misrepresentation, and deceit in connection with the purchase or sale of securities.",
      category: "Securities Fraud",
      authority: "SEC",
      severity: "critical" as const,
      keywords: [],
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
];

export const demoDashboardStats: DashboardStats = {
  totalViolations: 247,
  criticalViolations: 23,
  activeCalls: 8,
  complianceScore: 72,
  riskTrend: [
    { date: "Mon", score: 65 },
    { date: "Tue", score: 58 },
    { date: "Wed", score: 72 },
    { date: "Thu", score: 68 },
    { date: "Fri", score: 75 },
    { date: "Sat", score: 62 },
    { date: "Sun", score: 70 },
  ],
  violationsByType: [
    { category: "Securities Fraud", count: 45 },
    { category: "Best Interest", count: 38 },
    { category: "Suitability", count: 52 },
    { category: "Communications", count: 31 },
    { category: "Consumer Protection", count: 28 },
    { category: "Marketing", count: 22 },
    { category: "Record Keeping", count: 18 },
    { category: "Privacy", count: 13 },
  ],
  recentViolations: demoViolations as Violation[],
};
