import type { Violation, Call, DashboardStats } from "@/types";

export const demoTranscriptLines = [
  { speaker: "Agent", text: "Good morning! Thank you for calling RegPulse Financial Services. How can I help you today?", delay: 0 },
  { speaker: "Customer", text: "Hi, I'm interested in investment options. I have about $50,000 to invest.", delay: 3000 },
  { speaker: "Agent", text: "That's great! I have the perfect opportunity for you. Our proprietary trading algorithm has been generating consistent 20% monthly returns.", delay: 6000 },
  { speaker: "Customer", text: "20% monthly? That sounds incredible. Is that guaranteed?", delay: 10000 },
  { speaker: "Agent", text: "Absolutely! With our strategy, you're guaranteed to see those returns. There's virtually zero downside risk involved.", delay: 13000 },
  { speaker: "Customer", text: "Zero risk? That does sound too good to be true...", delay: 17000 },
  { speaker: "Agent", text: "I understand your concern, but trust me, this is a sure thing. Our past clients have never lost money. You really can't miss this opportunity.", delay: 20000 },
  { speaker: "Customer", text: "What about the fees? And do I need to sign anything?", delay: 25000 },
  { speaker: "Agent", text: "Don't worry about the paperwork - we can skip most of that. The fees are minimal and you can get started right now. This offer is only available for a limited time.", delay: 28000 },
  { speaker: "Customer", text: "I'm not sure I should rush into this...", delay: 33000 },
  { speaker: "Agent", text: "Let me share some of our client testimonials - every single one of them has seen amazing returns. This is the only investment option you'll ever need.", delay: 36000 },
];

export const demoViolations: Partial<Violation>[] = [
  {
    id: "demo-v1",
    severity: "critical",
    confidence: 97,
    description: "Guaranteed returns claim - stated '20% monthly returns' and 'guaranteed to see those returns'",
    transcript_excerpt: "Our proprietary trading algorithm has been generating consistent 20% monthly returns... you're guaranteed to see those returns.",
    timestamp_ms: 6000,
    ai_reasoning: "Direct violation of SEC Rule 10b-5. Making specific return guarantees is prohibited as it constitutes fraud in connection with securities.",
    status: "open",
    rule: {
      id: "r1",
      code: "SEC-10B-5",
      name: "Anti-Fraud Provision",
      description: "Prohibits fraud, misrepresentation, and deceit in connection with the purchase or sale of securities.",
      category: "Securities Fraud",
      authority: "SEC",
      severity: "critical",
      keywords: [],
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: "demo-v2",
    severity: "critical",
    confidence: 95,
    description: "Zero risk misrepresentation - claimed 'zero downside risk' for investment product",
    transcript_excerpt: "There's virtually zero downside risk involved.",
    timestamp_ms: 13000,
    ai_reasoning: "All investments carry risk. Claiming zero risk is a material misrepresentation that violates anti-fraud provisions.",
    status: "open",
    rule: {
      id: "r1",
      code: "SEC-10B-5",
      name: "Anti-Fraud Provision",
      description: "Prohibits fraud, misrepresentation, and deceit in connection with the purchase or sale of securities.",
      category: "Securities Fraud",
      authority: "SEC",
      severity: "critical",
      keywords: [],
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: "demo-v3",
    severity: "high",
    confidence: 88,
    description: "Suitability failure - recommended a single product without assessing customer needs or risk tolerance",
    transcript_excerpt: "I have the perfect opportunity for you... This is the only investment option you'll ever need.",
    timestamp_ms: 6000,
    ai_reasoning: "Agent failed to assess customer's investment objectives, risk tolerance, or financial situation before making a recommendation.",
    status: "open",
    rule: {
      id: "r3",
      code: "FINRA-2111",
      name: "Suitability",
      description: "Requires reasonable basis to believe recommendation is suitable for the customer.",
      category: "Suitability",
      authority: "FINRA",
      severity: "high",
      keywords: [],
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: "demo-v4",
    severity: "high",
    confidence: 92,
    description: "Pressure tactics and urgency - used 'limited time' offer to pressure customer decision",
    transcript_excerpt: "This offer is only available for a limited time.",
    timestamp_ms: 28000,
    ai_reasoning: "Creating artificial urgency violates FTC Act Section 5 prohibition on unfair or deceptive practices.",
    status: "open",
    rule: {
      id: "r5",
      code: "FTC-ACT-SEC5",
      name: "FTC Act Section 5",
      description: "Prohibits unfair or deceptive acts or practices in or affecting commerce.",
      category: "Consumer Protection",
      authority: "FTC",
      severity: "high",
      keywords: [],
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
  {
    id: "demo-v5",
    severity: "medium",
    confidence: 85,
    description: "Record keeping violation - suggested skipping required documentation",
    transcript_excerpt: "Don't worry about the paperwork - we can skip most of that.",
    timestamp_ms: 28000,
    ai_reasoning: "Suggesting to bypass required documentation violates Books and Records requirements under SEC Rule 204-2.",
    status: "open",
    rule: {
      id: "r7",
      code: "SEC-204-2",
      name: "Books and Records",
      description: "Requires investment advisers to maintain accurate books and records.",
      category: "Record Keeping",
      authority: "SEC",
      severity: "low",
      keywords: [],
      is_active: true,
      created_at: new Date().toISOString(),
    },
  },
];

export const demoCall: Partial<Call> = {
  id: "demo-call-1",
  agent_name: "Demo Agent",
  customer_name: "Demo Customer",
  status: "active",
  risk_score: 0,
  started_at: new Date().toISOString(),
};

export const demoDashboardStats: DashboardStats = {
  totalViolations: 247,
  criticalViolations: 23,
  activeCalls: 8,
  complianceScore: 72,
  riskTrend: [
    { date: "Mon", score: 65 },
    { date: "Tue", score: 58 },
    { date: "Wed", score: 72 },
    { date: "Thu", score: 68 },
    { date: "Fri", score: 75 },
    { date: "Sat", score: 62 },
    { date: "Sun", score: 70 },
  ],
  violationsByType: [
    { category: "Securities Fraud", count: 45 },
    { category: "Best Interest", count: 38 },
    { category: "Suitability", count: 52 },
    { category: "Communications", count: 31 },
    { category: "Consumer Protection", count: 28 },
    { category: "Marketing", count: 22 },
    { category: "Record Keeping", count: 18 },
    { category: "Privacy", count: 13 },
  ],
  recentViolations: demoViolations as Violation[],
};
